### ISSUE TITLE
Images don't seem to cycle correctly

### ISSUE THREAD

**Issue by NiccoloGranieri** [mczachurski/wallpapper#16]
Created a file with 16 images, and set it as wallpaper. Changing manually the time, the images don't seem to change with regularity as one would expect. Even if azimuth and altitude have been set from the suggested website. Any suggestion?

**Comment by ctw-braun** [comment]
watch here https://github.com/mczachurski/wallpapper/issues/12

**Comment by tommyparker** [comment]
I've been playing around with the azimuth and altitude data for a few days now and I think I've got it down more or less.

So my first step was to make my test colour palette (I'm making an illustrated wallpaper so I have that flexibility) and split a 24 hour day into the 16 images required by breaking it down into 1.5 hour palettes.
<img width="857" alt="screenshot 2018-09-28 18 24 14" src="https://user-images.githubusercontent.com/43587678/46223603-badfe900-c34b-11e8-8733-7dc7a3801db2.png">


I then used www.suncalc.org to see which timeline closely matched mine by simply changing the date and checking the slider at the top of the screen.
<img width="1309" alt="screenshot 2018-09-28 18 21 57" src="https://user-images.githubusercontent.com/43587678/46223554-9ab02a00-c34b-11e8-995b-c3e9c1334395.png">


After that, it was a simple case of using the altitude and azimuth data as the values for each interval.
```
    "fileName": "1.png",
    "isPrimary": true,
    "isForLight": true,
    "isForDark": false,
    "altitude": 15.42,
    "azimuth": 80.18,
    "time": "07:30 UTC+1"

**Comment by JohnSlaughter** [comment]
Wait...  time is a value?  Or is that for your internal use only?

**Comment by tommyparker** [comment]
Ah sorry, yes. Time is just an internal use value for my records.

**Comment by ctw-braun** [comment]
It's good to split a day into 16 images but i don't believe the time from dawn to sunrise isn't always 1.5 hours :) I wanna see to the closed time a picture from night to dawn to sunrise and then to the bright day :) I added also the json time value for internal use, because after a couple of time nobody knows on wich time is this. In my opinion it can't work correctly around the world without a reference to the log, lat. 

    "altitude": 15.42,
    "azimuth": 80.18,

Nobody knows on which location this is and without a time value can you not say "ah this is at 12:00 in my region". I don't know how Apple this calculate but on all Websites where u can calculate the sunrise  and sunset u must enter log, lat and a date/time value. This is the only way to get on a specific point the correct sunset time on a specific day. In my example i used the longest day of the year in my location 21. Jun 18 sunrise was around at 5:50 but now in September is the sunrise much later.

Also was it interesting which altitude and azimuth have i to use for the wallpaper? My location where i am or the pictures location on the day where i makes it? for example i have a holiday picture from australia and i life in europe there is a big time difference :) What do u think is to use for altitude
and azimuth?

**Comment by tommyparker** [comment]
The time and location is irrelevant as it's based on the position of the sun relative to the observer. Which means as long as you input the correct altitude and azimuth values, it'll work in sync with the daylight wherever you are.

Also, in theory, you could also do 1 main day image and 1 main night image and fill the remaining 14 image slots with a more detailed sunrise and sunset.

**Comment by JohnSlaughter** [comment]
I found that didn’t really work.  I set up a test every 15 minutes and it still only updated every hour/hour and a half.    It was a different image every time, the most accurate one when it did finally change, but it just doesn’t check that often to use the extra images.

**Comment by tommyparker** [comment]
Ah that's a shame – would be nice to have a smooth sunset transistion.

**Comment by JohnSlaughter** [comment]
If we knew what daemon triggered the check, we might be able to get it to fire more often. At the very least restart it, which would force an update. (Changing the clock forces an update, so there is a way to trigger it.)

**Comment by brandondadam** [comment]
Has anyone gotten time to successfully work? I think I was understanding, and created this json file:

    {
        "fileName": "1.png",
        "time": "2012-04-23T07:00:00Z"
    },
    {
        "fileName": "2.png",
        "time": "2012-04-23T09:00:00Z"
    },
    {
        "fileName": "3.png",
        "time": "2012-04-23T11:00:00Z"
    },
    {
        "fileName": "4.png",
        "time": "2012-04-23T12:00:00Z"
    },
    {
        "fileName": "5.png",
        "time": "2012-04-23T13:00:00Z"
    },
    {
        "fileName": "6.png",
        "time": "2012-04-23T14:00:00Z"
    },
    {
        "fileName": "7.png",
        "isPrimary": true,
        "time": "2012-04-23T15:00:00Z"
    },
    {
        "fileName": "8.png",
        "isForLight": true,
        "time": "2012-04-23T16:00:00Z"
    },
    {
        "fileName": "9.png",
        "time": "2012-04-23T17:00:00Z"
    },
    {
        "fileName": "10.png",
        "time": "2012-04-23T18:00:00Z"
    },
    {
        "fileName": "11.png",
        "time": "2012-04-23T19:00:00Z"
    },
    {
        "fileName": "12.png",
        "time": "2012-04-23T20:00:00Z"
    },
    {
        "fileName": "13.png",
        "time": "2012-04-23T21:00:00Z"
    },
    {
        "fileName": "14.png",
        "time": "2012-04-23T22:30:00Z"
    },
    {
        "fileName": "15.png",
        "time": "2012-04-23T23:45:00Z"
    },
    {
        "fileName": "16.png",
        "isForDark": true,
        "time": "2012-04-23T04:00:00Z"
    }


What is happening here is that I have a few images that cycle every hour from 8am-6pm. You might notice the times don't actually match up in UTC for those hours (I did some calculations based off how many hours my time was off and adjusted the json). So they actually cycle properly a that time now...

I noticed something weird though, the UTC conversion does not happen, which is why I was able to get away with manual conversions. The even weirder part is that images 15, 16, and 1 just randomly start converting themselves and show properly based off the UTC time. In other words, I have to do some manual conversions to get the images to appear at the desired time, but images 15, 16, 1 do their own thing and convert to local time. Has anyone else been able to successfully cycle through hours as predicted? 

I took a look at the source's indexing code, and the only thing I can think of is that the images don't get categorized properly into  sequenceInfo.ti, or when the imageMetadata is set something goes wrong. I'm not much of a swift developer, but the code looks pretty clean, so I'm wondering how ti is determined?

**Comment by brandondadam** [comment]
Has anyone discovered an issue when setting "isPrimary" in the JSON? IsPrimary seems to affect the sequence order, but I'm having trouble understand how. I even looked at how the sequence order was set in the generator file, and can't make sense of why isPrimary changes the images order.

**Comment by mczachurski** [comment]
Picture which is marked as "isPrimary" must to be added to the heic file as a first picture. Thanks to this that picture is visible as thumbnail in operating system.

**Comment by brandondadam** [comment]
Awesome! That did the trick. Thank you!

For future reference, is there clearer documentation on the json properties anywhere? I'm getting pretty creative about what kind of wallpappers I'm creating and something detailing the json structure would be really helpful! For example, is there any specific order the isForDark property should be in? I can't figure that out with trial and error, and this way people might not make the same mistake.

**Comment by vatologic** [comment]
@brandondadam The date is in the ISO 8601 format. With date, time and UTC. The JSON examples mention only Zulu (Z) as the base, but that can be changed to +01:00 or whatever the UTC offset in your zone is. 

I've noticed Mojave's wallpaper daemon (whichever one that may be) crashed when I used dates in the future, so I rigged my to be at least two days in the past. 

For people that want the thumbnails to work in MacOS Mojave, here's a way:
1. Save the wallpaper.heic file to /Library/Desktop Pictures (you need admin access). I know it's not the cleanest way - but that made the dynamic wallpapers show up with the proper 'dynamic' option in the dropdown menu when you change wallpapers.
2. Install ImageMagick with Homebrew; brew install imagemagick
3. Convert one reference frame to .heic; magick frame.png -resize 355x200! wallpaper.heic

The wallpaper itself and the thumbnail must have identical names. The resolution of MacOS's own thumbnails was 200 pixels high and 355 for the .heic files and 354 for the .jpg files. I've used the exclamation mark in the resize argument of ImageMagick since I just wanted to have some sort of reference, even though images may appear stretched in the preview - the wallpaper itself is unaffected. The reason why I didn't just made one in Photoshop; I wanted everything to come from one CLI script and I needed to have thumb creation on the fly.

**Comment by MikeKnowles** [comment]
Thanks @vatologic, your comment about the thumbnails helped me realize that my heic weren't cycling because of the file name. Once I renamed them to `Catalina.heic` it cycled them fine even though they're outside the read only root. (In `~/Library/Desktop\ Pictures/Catalina\ {Left,Right}/Catalina.heic` respectively)

You can confirm macOS is changing backgrounds based on messages from `com.apple.dynamicdesktop` in the Console.app
