### ISSUE TITLE
iOS 13 Dark Mode Support

### ISSUE THREAD

**Issue by asleepingpanda** [mczachurski/wallpapper#35]
iOS 13 offers a handful of stock wallpapers that have a specific look for Light Mode and a different look for Dark Mode (similar to what was introduced in macOS Mojave). I am hoping to be able to replicate the behavior in order to create my own iOS Dynamic Wallpapers.

**What has already been tried and did not work**

1. using this package to create a `.heic` with 2 images, one for Light and one for Dark
2. take the dynamic wallpaper from Catalina (`Dynamic.heic` in `Library/Desktop Wallpapers`) and send it to an iOS 13 device

I have not been able to find the `.heic` for the stock wallpapers inside of iOS. I would love to get some help finding the original files, decoding it, and then trying to replicate the meta data to see if this can even be done!

**Comment by mczachurski** [comment]
Hi, I didn't figure out any way to create that kind of wallpaper for iOS.

**Comment by shyd** [comment]
Hi, that is exactly what I just tried.
Did you make any progress on this? Looking forward to this 🚀

**Comment by MoOx** [comment]
I just know that an app for jailbreaked iPhone can do it DynaWall.

**Comment by mczachurski** [comment]
I did small investigation how "dynamic" wallpapers works on iPhone. In iOS 14 folder with single dynamic (light/dark) wallpaper looks like this:

![image](https://user-images.githubusercontent.com/6191974/104506837-341bac80-55e6-11eb-9c7f-3d4f792a67bf.png)

Thus we have here `HEIC` file. However when I’ve opened it I saw that it contains only one file, so this file is only for preview purposes in iPhone Settings app. Wallpaper settings we can find in `Wallpaper.plist` file:

![image](https://user-images.githubusercontent.com/6191974/104506934-56152f00-55e6-11eb-85c0-2b2ea1bc0dc9.png)

As you see here we have paths to `default` and `dark` wallpapers. Unfortunately we cannot send to that kind of wallpaper to the iPhone.

Only workaround of that issue is to use "Shortcuts" app. You can change wallpaper after sunrise/sunset for example.
