### ISSUE TITLE
Automatically generate JSON file for current location?

### ISSUE THREAD

**Issue by GoldenChaos** [mczachurski/wallpapper#5]
Hi there! I really want to use this, but I'm honestly getting stuck creating the JSON file. The example provided doesn't help me understand what the default settings should be, and I'd love if this could grab my current location and handle it automatically. Is that possible?

**Comment by mczachurski** [comment]
Application cannot generate JSON automatically because you have to provide information about position of the Sun when you take the photo. It's essence of dynamic wallpapers.

This site: https://keisan.casio.com/exec/system/1224682277 should help you with collectiing all mandatory information. You have to enter there position where photos were taken (very often it will be different position then your actual location) and the date. When you click execute button you will get altitude and azimuth of the sun during whole day. Now you have to match hours (coordinates) to your photos.

Of course I can also change the JSON structure and instead of azimuth/altitude you will have to provide location and the date when photos were taken, and then application will recalculate this altitude/azimuth, however I'm not sure that this will be a huge improvement.

**Comment by GoldenChaos** [comment]
In my case I have 16 abstract digital art pieces that I wish to put together - they have no actual location and time. What do I put in the JSON file in this case? I guess in that sense it's similar to the "solar gradients" wallpaper, it's not made up of real photos.

**Comment by mczachurski** [comment]
Even if this is not real photo you have to decide when the pictures should change. And in that case "when" it's not about hour but more about level of sunlight. So after sunset picture should change to darkest one. During whole year this will take place on different hour.

Application cannot deduct when photos should be changed, becouse it cannot guess your intentions.

Here you have metadata from Solar Gradients wallpaper: [solar-gradients.txt](https://github.com/mczachurski/wallpapper/files/2252275/solar-gradients.txt). However, you shouldn't use that coordinates thoughtlessly. Real power of dynamic wallpapers is that it will change to proper one on correct time of day.
